# Generated by Django 3.2.9 on 2021-12-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_state_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='mode',
        ),
    ]
