# Generated by Django 3.2.9 on 2021-12-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_rename_name_state_light_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='mode',
            field=models.CharField(default='auto', max_length=50),
            preserve_default=False,
        ),
    ]
